---
title: "Modelling Test"
author: "Josephine Baker"
date: "April 10, 2018"
output: github_document
---
Sankey Plots



```{r 1}
library(readr)
library(tidyverse)
library(plotly)
library(networkD3)
library(riverplot)
```


```{r 1.2}
bay_pop<- c(7000000,7128490,7190099,7200000,72578459,
            7379065,7500000,7600000,7654870)
pdx_pop<-c(2195039,2200000,2226009,2272500,2293904,
           2314747,2348278,2350940,2403920)
sea_pop<-c(3990394,3402039,3439809,3494830,3552815,
           3609617,3667042,3727097,3800489)

```
```{r 1.3}
migration<-read_csv("migration.csv")
migration<- migration%>%
  select(origin, destinations, n, year)
outflow2_pdx<-outflow2_pdx%>%
  rename(origin = origin_area)%>%
  rename(destinations = dest_area)%>%
  select(origin,destinations,year, n)

migration2<- rbind(as.data.frame(outflow2_pdx), as.data.frame(migration))


  
```



```{r 2}
migration3<- migration2%>%
  mutate(origin = ifelse(origin=="bay_area"|origin=="puget_sound_area",
                         origin, "other"))%>%
  mutate(destinations = ifelse(destinations=="bay_area"|destinations=="puget_sound_area"|destinations=="pdx",destinations, "other"))%>%
  group_by(origin, destinations, year)%>%
  summarize(n = sum(n))%>%
  arrange(year)

migration_org<- migration3%>%
  group_by(origin, year)%>%
  summarize(n = sum(n))%>%
  arrange(year)


migration_dest<- migration3%>%
  group_by(destinations, year)%>%
  summarize(n = sum(n))%>%
  arrange(year)

migration_org$id_org<-seq.int(nrow(migration_org))-1
migration_dest$id_dest<-seq.int(nrow(migration_dest))-1

migration4<- left_join(migration3, migration_org, by = c("origin", "year"))
migration5<- left_join(migration4, migration_dest, by = c("destinations", "year"))%>%
  group_by(origin, destinations, year)%>%
  summarize(n = sum(n), id_org = max(id_org), id_dest = max(id_dest))%>%
  arrange(year)%>%
  mutate(id_dest = id_dest+5)

```










```{r 2}
p <- plot_ly(
    type = "sankey",
    orientation = "h",

    node = list(
      label = c("B08", "S08", "P08", "O08",
                "B09", "S09", "P09", "O09"),
      color = c("blue", "blue", "blue", "blue", "blue", "blue"),
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = c(0,1,2,3,1,3),
      target = c(5,6,7,5,4,5),
      value =  c(8,4,2,3,4,2)
    )
  ) %>% 
  layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)

p

```



```{r 2}


p <- plot_ly(
    type = "sankey",
    orientation = "h",

    node = list(
      label = c("Bay Area 2008", 
                "Other 2008",
                "Seattle 2008",
                "Portland 2008",
                "Bay Area 2009", 
                "Other 2009",
                "Seattle 2009",
                "Portland 2009",
                "Bay Area 2010", 
                "Other 2010",
                "Seattle 2010",
                "Portland 2010",
                "Bay Area 2011", 
                "Other 2011",
                "Seattle 2011",
                "Portland 2011",
                "Bay Area 2012", 
                "Other 2012",
                "Seattle 2012",
                "Portland 2012",
                "Bay Area 2013", 
                "Other 2013",
                "Seattle 2013",
                "Portland 2013",
                "Bay Area 2014", 
                "Other 2014",
                "Seattle 2014",
                "Portland 2014",
                "Bay Area 2015", 
                "Other 2015",
                "Seattle 2015",
                "Portland 2015"
                ),
      color = c("pink", "other", "green", "orange",
                "pink", "other", "green", "orange",
                "pink", "other", "green", "orange",
                "pink", "other", "green", "orange",
                "pink", "other", "green", "orange",
                "pink", "other", "green", "orange",
                "pink", "other", "green", "orange",
                "pink", "other", "green", "orange"),
      pad = 15,
      thickness = 20,
      line = list(
        color = "black",
        width = 0.5
      )
    ),

    link = list(
      source = migration5$id_org,
      target = migration5$id_dest,
      value = migration5$n,
      label = migration5$origin
    )
  ) %>% 
  layout(
    title = "Basic Sankey Diagram",
    font = list(
      size = 10
    )
)



```




```{r fuckit}
makeRiver(nodes0,edges0,node_styles = styles0)
riverplot(b, add_mid_points = FALSE)


```