---
title: "Occupation Visualizations"
author: "Lucas Williams"
date: "May 3, 2018"
output: github_document
---
```{r}
library(tidyverse)
```
```{r}
pdx_occupations <- read.csv("C:\\Users\\Godot\\Documents\\sd-pdx-sea\\pdx_occupations.csv")
pdx_counties_occupations <- read.csv("C:\\Users\\Godot\\Documents\\sd-pdx-sea\\pdx_counties_occupations.csv")
sf_occupations <- read.csv("C:\\Users\\Godot\\Documents\\sd-pdx-sea\\sf_occupations.csv")
sf_counties_occupations <- read.csv("C:\\Users\\Godot\\Documents\\sd-pdx-sea\\sf_counties_occupations.csv")
sea_occupations <- read.csv("C:\\Users\\Godot\\Documents\\sd-pdx-sea\\sea_occupations.csv")
sea_counties_occupations <- read.csv("C:\\Users\\Godot\\Documents\\sd-pdx-sea\\sea_counties_occupations.csv")
```
```{r}
great_theme <- theme(axis.text.x = element_text(angle = 90))


#white/blue proportion collar by pdx county
pdx_class_county <- pdx_counties_occupations %>%
  mutate(year = as.integer(year)) %>%
  ggplot(aes(x=year, y=prop_county_class, col=job_class)) +
    geom_smooth(se=F) +
    facet_wrap(~county) +
    great_theme
pdx_class_county

#sector by pdx county
pdx_sector_county <- pdx_counties_occupations %>%
  mutate(year = as.numeric(year)) %>%
  ggplot(aes(x=year, y = prop_county_type, col = job_type)) +
    geom_smooth(se=F) +
    facet_wrap(~county) +
    theme(axis.text.x = element_text(angle = 90))
pdx_sector_county

#white/blues collar proportion pdx
pdx_class <- pdx_occupations %>%
  mutate(year=as.integer(year)) %>%
  ggplot(aes(x=year,y=job_class_prop, col=job_class)) +
    geom_smooth(se=F) +
    theme(axis.text.x = element_text(angle = 90))
pdx_class

#sector prop pdx
pdx_sector <- pdx_occupations %>%
  mutate(year=as.integer(year)) %>%
  ggplot(aes(x=year, y=job_type_prop, col=job_type)) +
    geom_smooth(se=F) +
    theme(axis.text.x = element_text(angle = 90))
pdx_sector

#white/blue proportion collar by sf county
sf_class_county <- sf_counties_occupations %>%
  ggplot(aes(x=year, y=prop_county_class, col=job_class)) +
    geom_smooth(se=F) +
    facet_wrap(~county) +
    theme(axis.text.x = element_text(angle = 90))
sf_class_county

#sector by sf county
sf_sector_county <- sf_counties_occupations %>%
  ggplot(aes(x=year, y = prop_county_type, col = job_type)) +
    geom_smooth(se=F) +
    facet_wrap(~county) +
    theme(axis.text.x = element_text(angle = 90))
sf_sector_county

#white/blues collar proportion sf
sf_class <- sf_occupations %>%
  ggplot(aes(x=year,y=job_class_prop, col=job_class)) +
    geom_smooth(se=F) +
    theme(axis.text.x = element_text(angle = 90))
sf_class

#sector prop sf
sf_sector <- sf_occupations %>%
  ggplot(aes(x=year, y=job_type_prop, col=job_type)) +
    geom_smooth(se=F) +
    theme(axis.text.x = element_text(angle = 90))
sf_sector
#white/blue proportion collar by sea county
sea_class_county <- sea_counties_occupations %>%
  ggplot(aes(x=year, y=prop_county_class, col=job_class)) +
    geom_smooth(se=F) +
    facet_wrap(~county) +
    theme(axis.text.x = element_text(angle = 90))
sea_class_county

#sector by sea county
sea_sector_county <- sea_counties_occupations %>%
  ggplot(aes(x=year, y = prop_county_type, col = job_type)) +
    geom_smooth(se=F) +
    facet_wrap(~county) +
    theme(axis.text.x = element_text(angle = 90))
sea_sector_county

#white/blues collar proportion sea
sea_class<- sea_occupations %>%
  ggplot(aes(x=year,y=job_class_prop, col=job_class)) +
    geom_smooth(se=F) +
    theme(axis.text.x = element_text(angle = 90))
sea_class

#sector prop sea
sea_sector<-sea_occupations %>%
  ggplot(aes(x=year, y=job_type_prop, col=job_type)) +
    geom_smooth(se=F) +
    theme(axis.text.x = element_text(angle = 90))
sea_sector
```